services:
  - type: worker
    name: shark-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_NAME
        value: shark_v8.db
      - key: PRIMARY_PROVIDER
        value: yfinance